Repository spotDL/spotify-downloader, pull requests merged in 2021-06, with the labels that each got.

#1303 Quality of life improvements
  spotdl/__main__.py
  spotdl/download/embed_metadata.py
  spotdl/download/ffmpeg.py
  spotdl/download/progressuiHandlers.py
  spotdl/search/audioProvider.py
  tests/test_downloader.py
  tests/test_ffmpeg.py
Labels: bugfix

#1315 Song gathering improvements
  spotdl/download/ffmpeg.py
  spotdl/search/audioProvider.py
  spotdl/search/songGatherer.py
Labels: bugfix, enhancement

#1233 Shorter filenames when path is too long
  spotdl/download/downloader.py
  spotdl/search/songGatherer.py
  tests/cassettes/test_download_long_artists_song.yaml
  tests/regressions.py
  tests/test_downloader.py
Labels: bugfix

#1311 Finally publish v3.6.2
  spotdl/download/downloader.py
  spotdl/download/ffmpeg.py
  spotdl/search/audioProvider.py
  spotdl/search/songGatherer.py
  tests/cassettes/test_download_a_playlist.yaml
  tests/cassettes/test_download_a_single_song.yaml
  tests/cassettes/test_download_an_album.yaml
  tests/cassettes/test_download_long_artists_song.yaml
  tests/cassettes/test_multiple_elements.yaml
  tests/cassettes/test_search_and_download.yaml
  tests/regressions.py
  tests/test_downloader.py
Labels: skip-changelog

#1328 Publish Version 3.6.3
  .github/workflows/spotify-downloader-ci.yml
  spotdl/download/downloader.py
  spotdl/search/songGatherer.py
Labels: skip-changelog
