Repository spotDL/spotify-downloader, pull requests merged in 2021-01, with the labels that each got.

#1054 readme Various fixes & changes
  README.md
Labels: enhancement

#1092 Discord Information
  .bettercodehub.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: enhancement

#1094 Dev-->Master, Discord Info & fix releasedrafter
  .bettercodehub.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/python-publish.yml
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: skip-changelog

#1076 Improved `saveFile` handling
  spotdl/download/progressHandlers.py
Labels: enhancement

#1093 Fix tests, setup CI
  .editorconfig
  .github/workflows/spotify-downloader-ci.yml
  mypy.ini
  spotdl/__main__.py
  spotdl/search/provider.py
  tests/cassettes/test_download_a_playlist.yaml
  tests/cassettes/test_download_a_single_song.yaml
  tests/cassettes/test_download_an_album.yaml
  tests/cassettes/test_multiple_elements.yaml
  tests/cassettes/test_search_and_download.yaml
  tests/test_entry_point.py
  tox.ini
Labels: enhancement

#1096 Refactor setup.py. Add setup.cfg. modify issue & PR templates.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  setup.cfg
  setup.py
Labels: enhancement

#1108 Fixing typo
  CONTRIBUTING.md
Labels: enhancement

#1107 Improved Temp File Handling
  spotdl/download/downloader.py
Labels: High Priority, bugfix

#1114 Publish to master from hotfix - Improved Temp File Handling (#1107)
  setup.py
  spotdl/download/downloader.py
Labels: skip-changelog

#1116 Fix setup.cfg & setup.py dev
  setup.cfg
  spotdl/__init__.py
  spotdl/__main__.py
Labels: bugfix

#1111 Finalizing Development branch
  .editorconfig
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/workflows/spotify-downloader-ci.yml
  CONTRIBUTING.md
  COREVALUES.md
  Design Docs/CORE VALUES.md
  setup.cfg
  setup.py
  spotdl/__init__.py
  spotdl/__main__.py
  spotdl/download/progressHandlers.py
  spotdl/search/provider.py
  tests/cassettes/test_download_a_playlist.yaml
  tests/cassettes/test_download_a_single_song.yaml
  tests/cassettes/test_download_an_album.yaml
  tests/cassettes/test_multiple_elements.yaml
  tests/cassettes/test_search_and_download.yaml
  tests/test_entry_point.py
  tox.ini
Labels: skip-changelog

#1117 fix disallowed chars matching for colons (:)
  spotdl/download/downloader.py
Labels: bugfix

#1128 fix disallowed chars matching for colons (:)
  spotdl/download/downloader.py
Labels: bugfix

#1122 Add basic tests for downloader.py
  .github/workflows/spotify-downloader-ci.yml
  spotdl/download/downloader.py
  tests/cassettes/test_download_single_song.yaml
  tests/test_downloader.py
  tox.ini
Labels: enhancement

#1131 Dev to Master
  .github/workflows/spotify-downloader-ci.yml
  setup.cfg
  spotdl/download/downloader.py
  spotdl/search/provider.py
  tests/cassettes/test_download_single_song.yaml
  tests/regressions.py
  tests/test_downloader.py
  tox.ini
Labels: skip-changelog

#1133 Fix workflows
  .github/workflows/python-publish.yml
  .github/workflows/spotify-downloader-ci.yml
Labels: bugfix

#1118 New PR Template & Update stalebot configs
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/stale.yml
  .gitignore
Labels: enhancement

#1137 Installation guide.
  INSTALLATION.md
  static/ADD_TO_PATH.png
  static/POWERSHELL.png
Labels: enhancement
