Repository spotDL/spotify-downloader, pull requests merged in 2021-07, with the labels that each got.

#1347 Bring new v4 issue templates to v3 repository
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: META, enhancement

#1354 Publish v3.7.1
  spotdl/download/downloader.py
  spotdl/search/song_gatherer.py
Labels: skip-changelog

#1357 bugfix: fixed m3u issues
  spotdl/download/downloader.py
  spotdl/parsers/query_parser.py
  spotdl/providers/provider_utils.py
  spotdl/providers/yt_provider.py
  spotdl/providers/ytm_provider.py
  spotdl/search/song_gatherer.py
  spotdl/search/song_object.py
Labels: enhancement

#1360 bugfix: fixed ytdl error reporting
  spotdl/download/downloader.py
  spotdl/download/ffmpeg.py
  spotdl/download/progress_ui_handler.py
Labels: bugfix

#1361 Publish version 3.7.2
  setup.cfg
  spotdl/download/downloader.py
  spotdl/download/ffmpeg.py
  spotdl/download/progress_ui_handler.py
  spotdl/parsers/query_parser.py
  spotdl/providers/provider_utils.py
  spotdl/providers/yt_provider.py
  spotdl/providers/ytm_provider.py
  spotdl/search/song_gatherer.py
  spotdl/search/song_object.py
Labels: skip-changelog
