Repository spotDL/spotify-downloader, pull requests merged in 2021-03, with the labels that each got.

#1194 Publish v3.3.3
  setup.cfg
  spotdl/__init__.py
  spotdl/download/downloader.py
  spotdl/search/provider.py
  spotdl/search/utils.py
  tests/test_provider.py
Labels: skip-changelog

#1195 added disc number metadata
  spotdl/download/downloader.py
  spotdl/search/songObj.py
Labels: enhancement

#1208 get all artist tracks
  spotdl/__main__.py
  spotdl/search/utils.py
Labels: enhancement

#1204 Publish Version 3.4.0
  .github/workflows/spotify-downloader-ci.yml
  setup.cfg
  spotdl/__init__.py
  spotdl/__main__.py
  spotdl/download/downloader.py
  spotdl/search/provider.py
  spotdl/search/songObj.py
  spotdl/search/utils.py
  tests/cassettes/test_download_a_playlist.yaml
  tests/cassettes/test_download_a_single_song.yaml
  tests/cassettes/test_download_an_album.yaml
  tests/cassettes/test_download_single_song.yaml
  tests/cassettes/test_multiple_elements.yaml
  tests/cassettes/test_search_and_download.yaml
  tests/test_downloader.py
  tests/utils/tracking_files.py
Labels: skip-changelog

#1216 fixed none type error when getting album
  spotdl/search/provider.py
Labels: bugfix

#1217 Publish v3.4.1
  .gitignore
  setup.cfg
  spotdl/search/provider.py
  spotdl/search/utils.py
  tests/cassettes/test_download_a_playlist.yaml
  tests/cassettes/test_download_a_single_song.yaml
  tests/cassettes/test_download_all_artist_tracks.yaml
  tests/cassettes/test_download_an_album.yaml
  tests/cassettes/test_download_single_song.yaml
  tests/cassettes/test_multiple_elements.yaml
  tests/cassettes/test_search_and_download.yaml
  tests/test_entry_point.py
Labels: skip-changelog

#1221 v3.4.2 - Update provider.py (#1218)
  spotdl/search/provider.py
Labels: skip-changelog

#1215 Fix MikhailZex GitHub's link
  README.md
Labels: enhancement

#1098 Switch to rich
  setup.cfg
  spotdl/__main__.py
  spotdl/download/downloader.py
  spotdl/download/progressHandlers.py
  spotdl/search/songObj.py
  tests/cassettes/test_download_a_playlist.yaml
  tests/cassettes/test_download_a_single_song.yaml
  tests/cassettes/test_download_an_album.yaml
  tests/cassettes/test_download_single_song.yaml
  tests/cassettes/test_multiple_elements.yaml
  tests/cassettes/test_search_and_download.yaml
  tests/test_downloader.py
  tests/test_entry_point.py
Labels: enhancement

#1232 Publish v3.5.0
  .gitignore
  README.md
  setup.cfg
  spotdl/__main__.py
  spotdl/download/downloader.py
  spotdl/download/progressHandlers.py
  spotdl/search/songObj.py
  spotdl/search/spotifyClient.py
  spotdl/search/utils.py
  tests/cassettes/test_download_a_playlist.yaml
  tests/cassettes/test_download_a_single_song.yaml
  tests/cassettes/test_download_all_artist_tracks.yaml
  tests/cassettes/test_download_an_album.yaml
  tests/cassettes/test_download_single_song.yaml
  tests/cassettes/test_multiple_elements.yaml
  tests/cassettes/test_search_and_download.yaml
  tests/test_downloader.py
  tests/test_entry_point.py
Labels: skip-changelog

#1224 check errors from ffmpeg sub process
  .github/workflows/spotify-downloader-ci.yml
  setup.cfg
  spotdl/__main__.py
  spotdl/download/downloader.py
  spotdl/download/ffmpeg.py
  tests/test_downloader.py
  tests/test_entry_point.py
  tests/test_ffmpeg.py
Labels: enhancement
