Repository spotDL/spotify-downloader, pull requests merged in 2021-05, with the labels that each got.

#1276 Remove FFmpeg normalization causing "quiet" songs.
  spotdl/download/downloader.py
  spotdl/download/ffmpeg.py
Labels: enhancement

#1240 Saved Songs Download and User Authentication
  .gitignore
  spotdl/__main__.py
  spotdl/search/__init__.py
  spotdl/search/spotifyClient.py
  spotdl/search/utils.py
  tests/test_entry_point.py
Labels: enhancement

#1290 regenerate cassettes
  tests/cassettes/test_download_a_playlist.yaml
  tests/cassettes/test_download_a_single_song.yaml
  tests/cassettes/test_download_an_album.yaml
  tests/cassettes/test_download_single_song.yaml
  tests/cassettes/test_multiple_elements.yaml
  tests/cassettes/test_search_and_download.yaml
Labels: bugfix

#1289 Use ffmpeg_path to check for version
  spotdl/download/ffmpeg.py
Labels: bugfix

#1287 Skip already downloaded songs before doing youtube search
  spotdl/__main__.py
  spotdl/download/downloader.py
  spotdl/search/provider.py
  spotdl/search/songObj.py
  spotdl/search/utils.py
Labels: enhancement

#1285 Fix security risk
  spotdl/download/downloader.py
  spotdl/download/ffmpeg.py
  tests/test_downloader.py
Labels: bugfix

#1279 Song matching improvements
  setup.cfg
  spotdl/search/provider.py
  tests/cassettes/test_download_a_playlist.yaml
  tests/cassettes/test_download_a_single_song.yaml
  tests/cassettes/test_download_an_album.yaml
  tests/cassettes/test_download_single_song.yaml
  tests/cassettes/test_multiple_elements.yaml
  tests/cassettes/test_search_and_download.yaml
Labels: bugfix, enhancement

#1284 Artist songs fixes
  spotdl/search/utils.py
Labels: bugfix, enhancement

#1244 More output formats
  .gitignore
  spotdl/__main__.py
  spotdl/download/__init__.py
  spotdl/download/downloader.py
  spotdl/download/embed_metadata.py
  spotdl/download/ffmpeg.py
  spotdl/search/songObj.py
  tests/test_downloader.py
  tests/test_ffmpeg.py
Labels: enhancement

#1291 Publish v3.6.0
  .github/workflows/spotify-downloader-ci.yml
  .gitignore
  README.md
  docs/INSTALLATION.md
  setup.cfg
  spotdl/__main__.py
  spotdl/download/__init__.py
  spotdl/download/downloader.py
  spotdl/download/embed_metadata.py
  spotdl/download/ffmpeg.py
  spotdl/search/__init__.py
  spotdl/search/provider.py
  spotdl/search/songObj.py
  spotdl/search/spotifyClient.py
  spotdl/search/utils.py
  tests/cassettes/test_download_a_playlist.yaml
  tests/cassettes/test_download_a_single_song.yaml
  tests/cassettes/test_download_an_album.yaml
  tests/cassettes/test_download_single_song.yaml
  tests/cassettes/test_multiple_elements.yaml
  tests/cassettes/test_search_and_download.yaml
  tests/regressions.py
  tests/test_downloader.py
  tests/test_entry_point.py
  tests/test_ffmpeg.py
Labels: skip-changelog

#1275 Some Code Cleanup
  spotdl/__init__.py
  spotdl/__main__.py
  spotdl/download/__init__.py
  spotdl/download/downloader.py
  spotdl/download/progressuiHandlers.py
  spotdl/download/trackingfileHandlers.py
  spotdl/search/__init__.py
  spotdl/search/audioProvider.py
  spotdl/search/metadataProvider.py
  spotdl/search/songGatherer.py
  spotdl/search/songObj.py
  spotdl/search/spotifyClient.py
  spotdl/search/utils.py
  tests/regressions.py
  tests/test_downloader.py
  tests/test_entry_point.py
  tests/test_ffmpeg.py
  tests/test_provider.py
  tests/utils/tracking_files.py
  tox.ini
Labels: enhancement

#1296 Publish Version 3.6.1
  .gitattributes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/CONTRIBUTING.md
  docs/CORE_VALUES.md
  docs/INSTALLATION.md
  docs/code/CODE_GUIDELINES.md
  docs/code/MODULES.md
  docs/code/OOP_REFRESHER.md
  docs/code/download/downloader.md
  docs/code/download/ffmpeg.md
  docs/code/download/progressHandlers.md
  docs/code/search/provider.md
  docs/code/search/songObj.md
  docs/code/search/spotifyClient.md
  docs/code/search/utils.md
  docs/design/INTERFACES.md
  docs/design/PURPOSES.md
  setup.cfg
  spotdl/__init__.py
  spotdl/__main__.py
  spotdl/download/__init__.py
  spotdl/download/downloader.py
  spotdl/download/embed_metadata.py
  spotdl/download/progressuiHandlers.py
  spotdl/download/trackingfileHandlers.py
  spotdl/search/__init__.py
  spotdl/search/audioProvider.py
  spotdl/search/metadataProvider.py
  spotdl/search/songGatherer.py
  spotdl/search/songObj.py
  spotdl/search/spotifyClient.py
  spotdl/search/utils.py
  tests/README.md
  tests/regressions.py
  tests/test_downloader.py
  tests/test_entry_point.py
  tests/test_ffmpeg.py
  tests/test_provider.py
  tests/utils/tracking_files.py
  tox.ini
Labels: skip-changelog
