Repository spotDL/spotify-downloader, pull requests merged in 2021-02, with the labels that each got.

#1157 Use argparse instead of raw `sys.argv`
  spotdl/__main__.py
  tests/test_entry_point.py
Labels: enhancement

#1159 Fixed Termux setup script.
  README.md
  termux/setup_spotdl.sh
  termux/termux-url-opener
Labels: bugfix, enhancement

#1162 Colon error fix
  spotdl/download/progressHandlers.py
Labels: bugfix

#1177 Fixed TypeError when downloading tracks
  spotdl/search/provider.py
Labels: High Priority, bugfix

#1164 Skip song if track is empty.
  spotdl/search/utils.py
Labels: bugfix

#1171 Dev to Master
  .github/workflows/spotify-downloader-ci.yml
  setup.cfg
  spotdl/__init__.py
  spotdl/__main__.py
  spotdl/download/__init__.py
  spotdl/download/downloader.py
  spotdl/download/progressHandlers.py
  spotdl/search/__init__.py
  spotdl/search/provider.py
  spotdl/search/songObj.py
  spotdl/search/spotifyClient.py
  spotdl/search/utils.py
  tests/regressions.py
  tests/test_entry_point.py
  tox.ini
Labels: skip-changelog

#1176 always include main artist
  spotdl/download/downloader.py
Labels: bugfix
