Repository spotDL/spotify-downloader, pull requests merged in 2021-04, with the labels that each got.

#1241 Publish Version 3.5.1
  .github/workflows/spotify-downloader-ci.yml
  INSTALLATION.md
  setup.cfg
  spotdl/__main__.py
  spotdl/download/downloader.py
  spotdl/download/ffmpeg.py
  tests/regressions.py
  tests/test_downloader.py
  tests/test_entry_point.py
  tests/test_ffmpeg.py
Labels: skip-changelog

#1252 ffmpeg executable path
  spotdl/__main__.py
  spotdl/download/downloader.py
  spotdl/download/ffmpeg.py
  tests/test_entry_point.py
Labels: enhancement

#1142 Hide KeyboardInterrupt error when process is terminated.
  spotdl/__main__.py
  tests/README.md
Labels: enhancement

#1254 subprocess: don't use shell
  spotdl/download/ffmpeg.py
Labels: enhancement

#1250 Song matching imprvovements
  spotdl/search/provider.py
Labels: enhancement

#1257 Readme and documentation improvements
  .bettercodehub.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  COREVALUES.md
  Code Docs/codeGuidelines.md
  Code Docs/download/downloader.md
  Code Docs/download/progressHandlers.md
  Code Docs/modules.md
  Code Docs/oopRefresher.md
  Code Docs/search/provider.md
  Code Docs/search/songObj.md
  Code Docs/search/spotifyClient.md
  Code Docs/search/utils.md
  Design Docs/INTERFACES.md
  Design Docs/PURPOSES.md
  LICENSE
  README.md
  docs/CONTRIBUTING.md
  docs/CORE_VALUES.md
  docs/INSTALLATION.md
  docs/code/CODE_GUIDELINES.md
  docs/code/MODULES.md
  docs/code/OOP_REFRESHER.md
  docs/code/download/downloader.md
  docs/code/download/ffmpeg.md
  docs/code/download/progressHandlers.md
  docs/code/search/provider.md
  docs/code/search/songObj.md
  docs/code/search/spotifyClient.md
  docs/code/search/utils.md
  docs/design/INTERFACES.md
  docs/design/PURPOSES.md
  docs/static/ADD_TO_PATH.png
  docs/static/POWERSHELL.png
  docs/static/logo-transparent.png
  docs/static/logo.png
  tests/README.md
Labels: enhancement

#1259 Publish version 3.5.2
  .bettercodehub.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/workflows/spotify-downloader-ci.yml
  CONTRIBUTING.md
  COREVALUES.md
  Code Docs/codeGuidelines.md
  Code Docs/download/downloader.md
  Code Docs/download/progressHandlers.md
  Code Docs/modules.md
  Code Docs/oopRefresher.md
  Code Docs/search/provider.md
  Code Docs/search/songObj.md
  Code Docs/search/spotifyClient.md
  Code Docs/search/utils.md
  Design Docs/INTERFACES.md
  Design Docs/PURPOSES.md
  LICENSE
  README.md
  dev utils/classLNC.py
  dev utils/fixSongLen.py
  dev utils/funcLNC.py
  dev utils/spotdlTF.py
  dev utils/totalLNC.py
  docs/CONTRIBUTING.md
  docs/CORE_VALUES.md
  docs/INSTALLATION.md
  docs/code/CODE_GUIDELINES.md
  docs/code/MODULES.md
  docs/code/OOP_REFRESHER.md
  docs/code/download/downloader.md
  docs/code/download/ffmpeg.md
  docs/code/download/progressHandlers.md
  docs/code/search/provider.md
  docs/code/search/songObj.md
  docs/code/search/spotifyClient.md
  docs/code/search/utils.md
  docs/design/INTERFACES.md
  docs/design/PURPOSES.md
  docs/static/ADD_TO_PATH.png
  docs/static/POWERSHELL.png
  docs/static/logo-transparent.png
  docs/static/logo.png
  setup.cfg
  spotdl/__main__.py
  spotdl/download/downloader.py
  spotdl/download/ffmpeg.py
  spotdl/search/provider.py
  tests/README.md
  tests/test_entry_point.py
Labels: skip-changelog

#1274 ignore .cache and other hidden files
  .gitignore
  tests/regressions.py
Labels: bugfix
